### ISSUE TITLE
how do I set this up

### ISSUE THREAD

**Issue by Cogginshome** [Loafdude/xapman#1]
what is this meant to run on and how would I set it up?

I currently have a XAP800 and XAP400 I would like to use this with.
ether from by headless Ubuntu server or the pi that's talking rs485 to the heat pump

**Comment by Loafdude** [comment]
It is designed to run on linux but any *nix with serial support in python should be fine.

You could run it from the command line like this
```
export MQTT_HOST='10.9.9.100'
export MQTT_PORT='1883'
export MQTT_ROOT='Home/Audio/'
export SERIAL_PORT='/dev/ttyS0'
export BAUD_RATE=38400
export RAMP_RATE=6
/usr/bin/python3 /usr/xapman/go.py
```
