### ISSUE TITLE
use with MQTT with password

### ISSUE THREAD

**Issue by Cogginshome** [Loafdude/xapman#3]
I'm trying to find where I can pass my user and password to the Paho-MQTT
I need a line like the below as best I can tell from the paho doc [https://techoverflow.net/2021/12/27/how-to-set-username-password-in-paho-mqtt/](url)
client.username_pw_set("myusername", "mypassword")
just not finding the python file

**Comment by Loafdude** [comment]
Hi

There is currently no provision for user/pass but it is quite easy to add

in mqtt.py modify the conn function with your user/pass. You could also setup the and pull enviroment variables from your OS 
```
    def conn(self):
        client.username_pw_set("myusername", "aeNg8aibai0oiloo7xiad1iaju1uch")
        self.connect(MQTT_HOST, int(MQTT_PORT), 60)
```

**Comment by Cogginshome** [comment]
hum 

not quite    
I get a failure on that with the trace back saying 

mqtt.py", line 27, in conn
client.username_pw_set("user name", "pasword")
NameError: name 'client' is not defined

**Comment by Loafdude** [comment]
Ah sorry that should be self.username_pw_set()

**Comment by Cogginshome** [comment]
yes I just figured that out and was going to say that

**Comment by Cogginshome** [comment]
For any future users  the below works     

def conn(self):
        self.username_pw_set("USER", "Password")
        self.connect(MQTT_HOST, int(MQTT_PORT), 60)
